changelog:
  categories:
    - title: 🚀 Outros
      labels:
        - '*'
    - title: 🚀 Novas Funcionalidades
      labels:
        - 'feature'
        - 'enhancement'
    - title: 🐛 Correções de Bugs
      labels:
        - 'bug'
        - 'fix'
    - title: 🛠️ Melhorias
      labels:
        - 'improvement'
        - 'refactor'
        - 'optimization'
    - title: 📝 Documentação
      labels:
        - 'documentation'
        - 'docs'   
  include: 
    commits: true
