x-airflow-common: &airflow-common
  build:
    context: .
  environment: &airflow-common-env
    AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: '${AIRFLOW_TIMEZONE}'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
    AIRFLOW__CORE__EXECUTOR: '${AIRFLOW_EXECUTOR}'
    AIRFLOW__CORE__FERNET_KEY: '${AIRFLOW_FERNET_KEY}'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}'
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE: 'false'
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY: 'false'
    AIRFLOW__SMTP__SMTP_HOST: '${SMTP_HOST}'
    AIRFLOW__SMTP__SMTP_MAIL_FROM: '${SMTP_FROM}'
    AIRFLOW__SMTP__SMTP_PORT: '${SMTP_PORT}'
    AIRFLOW__SMTP__SMTP_STARTTLS: 'true'
    AIRFLOW__SMTP__SMTP_USER: '${SMTP_USER}'
    AIRFLOW__SMTP__SMTP_PASSWORD: '${SMTP_PASSWORD}'
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: '${AIRFLOW_TIMEZONE}'
    AIRFLOW__WEBSERVER__SECRET_KEY: '${AIRFLOW_SECRET_KEY}'
    AIRFLOW__WEBSERVER__WORKERS: '${AIRFLOW_WORKERS}'

    _AIRFLOW_DB_UPGRADE: 'true'
    _AIRFLOW_WWW_USER_CREATE: 'true'
    _AIRFLOW_WWW_USER_USERNAME: '${AIRFLOW_USER}'
    _AIRFLOW_WWW_USER_PASSWORD: '${AIRFLOW_PASSWORD}'

    AIRFLOW_CONN_EXAMPLE_DATABASE_CONN: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}'

    RO_DOU__DAG_CONF_DIR: '${RO_DOU_DAG_CONF_DIR}'

  volumes:
    - ./src:/opt/airflow/dags/ro_dou_src
    - ./mnt/airflow-logs:/opt/airflow/logs
    - ./dag_confs:/opt/airflow/dags/ro_dou/dag_confs
    - ./dag_load_inlabs:/opt/airflow/dags/dag_load_inlabs
    - ./tests:/opt/airflow/tests
    - ./schemas:/opt/airflow/schemas
  user: '${AIRFLOW_UID:-50000}:0'
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./mnt/pgdata:/var/lib/postgresql/data
      - ./dag_load_inlabs/sql/:/sql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 5s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8080/health']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always
