name: CI Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ro-dou
      uses: actions/checkout@v3
      with:
        path: Ro-dou

    - name: Create .env for CI from example
      run: |
        # Copy .env.example to .env so Makefile include .env won't fail in CI
        cp Ro-dou/.env.example Ro-dou/.env || true

    - name: Run docker-compose
      run: cd Ro-dou && make run

    - name: run tests
      run: cd Ro-dou && make tests
